import type { Badge } from './types';

export type BadgeCategory = 'workout' | 'game' | 'nutrition';

export interface BadgeDefinition {
  id: string;
  nameEn: string;
  nameTh: string;
  description: string;
  icon: string;
  requirement: string;
  category: BadgeCategory;
  target: number;
}

// Central badge catalog for the app (Workout / Game / Nutrition)
export const BADGE_DEFINITIONS: BadgeDefinition[] = [
  {
    id: 'welcome_first_login',
    nameEn: 'KAYA First Light',
    nameTh: 'แสงแรกแห่ง KAYA',
    description: 'Celebrate your very first login and the start of your wellness journey',
    icon: '🌟',
    requirement: 'เข้าสู่ระบบครั้งแรก',
    category: 'workout',
    target: 1,
  },
  {
    id: 'workout_first',
    nameEn: 'First Workout',
    nameTh: 'ออกกำลังกายครั้งแรก',
    description: 'Complete your first workout session',
    icon: '🏃',
    requirement: 'ออกกำลังกายครบ 1 ครั้ง',
    category: 'workout',
    target: 1,
  },
  {
    id: 'workout_7_sessions',
    nameEn: 'Consistency 7',
    nameTh: 'นักสู้ 7 ครั้ง',
    description: 'Complete 7 workout sessions',
    icon: '🔥',
    requirement: 'ออกกำลังกายสะสมครบ 7 ครั้ง',
    category: 'workout',
    target: 7,
  },
  {
    id: 'workout_15_sessions',
    nameEn: 'Consistency 15',
    nameTh: 'นักสู้ 15 ครั้ง',
    description: 'Complete 15 workout sessions',
    icon: '💪',
    requirement: 'ออกกำลังกายสะสมครบ 15 ครั้ง',
    category: 'workout',
    target: 15,
  },
  {
    id: 'workout_30_sessions',
    nameEn: 'Consistency 30',
    nameTh: 'นักสู้ 30 ครั้ง',
    description: 'Complete 30 workout sessions',
    icon: '🏆',
    requirement: 'ออกกำลังกายสะสมครบ 30 ครั้ง',
    category: 'workout',
    target: 30,
  },
  {
    id: 'workout_50_minutes',
    nameEn: '50 Minute Engine',
    nameTh: 'รวมเวลา 50 นาที',
    description: 'Accumulate 50 workout minutes',
    icon: '⏱️',
    requirement: 'เวลาออกกำลังกายสะสมครบ 50 นาที',
    category: 'workout',
    target: 3000,
  },
  {
    id: 'workout_120_minutes',
    nameEn: '2 Hour Engine',
    nameTh: 'รวมเวลา 2 ชั่วโมง',
    description: 'Accumulate 2 workout hours',
    icon: '⏱️',
    requirement: 'เวลาออกกำลังกายสะสมครบ 2 ชั่วโมง',
    category: 'workout',
    target: 7200,
  },
  {
    id: 'workout_300_minutes',
    nameEn: '5 Hour Engine',
    nameTh: 'รวมเวลา 5 ชั่วโมง',
    description: 'Accumulate 5 workout hours',
    icon: '🔥',
    requirement: 'เวลาออกกำลังกายสะสมครบ 5 ชั่วโมง',
    category: 'workout',
    target: 18000,
  },
  {
    id: 'workout_1000_calories',
    nameEn: 'Calorie Burner 1K',
    nameTh: 'เผาผลาญ 1,000 แคล',
    description: 'Burn total 1,000 calories',
    icon: '⭐',
    requirement: 'เผาผลาญสะสมครบ 1,000 แคลอรี',
    category: 'workout',
    target: 1000,
  },
  {
    id: 'workout_5000_calories',
    nameEn: 'Calorie Burner 5K',
    nameTh: 'เผาผลาญ 5,000 แคล',
    description: 'Burn total 5,000 calories',
    icon: '⚡',
    requirement: 'เผาผลาญสะสมครบ 5,000 แคลอรี',
    category: 'workout',
    target: 5000,
  },
  {
    id: 'workout_streak_current_3',
    nameEn: 'Momentum 3',
    nameTh: 'ต่อเนื่อง 3 ครั้ง',
    description: 'Keep workout momentum with less than 24 hours between sessions for 3 sessions',
    icon: '⚡',
    requirement: 'ออกกำลังกายต่อเนื่อง (ไม่เกิน 24 ชม.) 3 ครั้ง',
    category: 'workout',
    target: 3,
  },
  {
    id: 'workout_streak_current_7',
    nameEn: 'Momentum 7',
    nameTh: 'ต่อเนื่อง 7 ครั้ง',
    description: 'Maintain workout continuity with less than 24 hours between sessions for 7 sessions',
    icon: '🔥',
    requirement: 'ออกกำลังกายต่อเนื่อง (ไม่เกิน 24 ชม.) 7 ครั้ง',
    category: 'workout',
    target: 7,
  },
  {
    id: 'workout_streak_record_10',
    nameEn: 'Streak Record 10',
    nameTh: 'สถิติต่อเนื่อง 10 ครั้ง',
    description: 'Reach an all-time best workout streak of 10 sessions',
    icon: '🏆',
    requirement: 'ทำสถิติต่อเนื่องสูงสุดครบ 10 ครั้ง',
    category: 'workout',
    target: 10,
  },
  {
    id: 'workout_streak_record_30',
    nameEn: 'Streak Record 30',
    nameTh: 'สถิติต่อเนื่อง 30 ครั้ง',
    description: 'Reach an all-time best workout streak of 30 sessions',
    icon: '⭐',
    requirement: 'ทำสถิติต่อเนื่องสูงสุดครบ 30 ครั้ง',
    category: 'workout',
    target: 30,
  },
  {
    id: 'game_first',
    nameEn: 'Game Starter',
    nameTh: 'เล่นเกมครั้งแรก',
    description: 'Play any game once',
    icon: '🎮',
    requirement: 'เล่นเกมครบ 1 รอบ',
    category: 'game',
    target: 1,
  },
  {
    id: 'game_25_sessions',
    nameEn: 'Arcade Regular',
    nameTh: 'สายเกม 25 รอบ',
    description: 'Play games 25 times',
    icon: '🏆',
    requirement: 'เล่นเกมสะสมครบ 25 รอบ',
    category: 'game',
    target: 25,
  },
  {
    id: 'game_5_sessions',
    nameEn: 'Game Rookie 5',
    nameTh: 'เกมเมอร์ 5 รอบ',
    description: 'Play games 5 times',
    icon: '🎯',
    requirement: 'เล่นเกมสะสมครบ 5 รอบ',
    category: 'game',
    target: 5,
  },
  {
    id: 'game_50_sessions',
    nameEn: 'Arcade Elite 50',
    nameTh: 'สายเกม 50 รอบ',
    description: 'Play games 50 times',
    icon: '🏆',
    requirement: 'เล่นเกมสะสมครบ 50 รอบ',
    category: 'game',
    target: 50,
  },
  {
    id: 'game_100_sessions',
    nameEn: 'Arcade Legend 100',
    nameTh: 'สายเกม 100 รอบ',
    description: 'Play games 100 times',
    icon: '⭐',
    requirement: 'เล่นเกมสะสมครบ 100 รอบ',
    category: 'game',
    target: 100,
  },
  {
    id: 'nutrition_first_log',
    nameEn: 'Food Logger',
    nameTh: 'บันทึกอาหารครั้งแรก',
    description: 'Save your first nutrition log',
    icon: '🥗',
    requirement: 'บันทึกโภชนาการครบ 1 ครั้ง',
    category: 'nutrition',
    target: 1,
  },
  {
    id: 'nutrition_7_logs',
    nameEn: 'Nutrition Week',
    nameTh: 'บันทึกโภชนาการ 7 ครั้ง',
    description: 'Save 7 nutrition logs',
    icon: '📘',
    requirement: 'บันทึกโภชนาการสะสมครบ 7 ครั้ง',
    category: 'nutrition',
    target: 7,
  },
  {
    id: 'nutrition_14_logs',
    nameEn: 'Nutrition 14',
    nameTh: 'บันทึกโภชนาการ 14 ครั้ง',
    description: 'Save 14 nutrition logs',
    icon: '📘',
    requirement: 'บันทึกโภชนาการสะสมครบ 14 ครั้ง',
    category: 'nutrition',
    target: 14,
  },
  {
    id: 'nutrition_30_logs',
    nameEn: 'Nutrition 30',
    nameTh: 'บันทึกโภชนาการ 30 ครั้ง',
    description: 'Save 30 nutrition logs',
    icon: '🥗',
    requirement: 'บันทึกโภชนาการสะสมครบ 30 ครั้ง',
    category: 'nutrition',
    target: 30,
  },
  {
    id: 'nutrition_hydration_goal',
    nameEn: 'Hydration Hero',
    nameTh: 'ดื่มน้ำครบเป้า',
    description: 'Reach water goal (8 glasses) in a day',
    icon: '💧',
    requirement: 'ทำเป้าดื่มน้ำครบ 8 แก้วใน 1 วัน',
    category: 'nutrition',
    target: 1,
  },
  {
    id: 'nutrition_hydration_7_days',
    nameEn: 'Hydration 7 Days',
    nameTh: 'ดื่มน้ำครบเป้า 7 วัน',
    description: 'Reach water goal in 7 different days',
    icon: '💧',
    requirement: 'ทำเป้าดื่มน้ำครบ 8 แก้ว สะสม 7 วัน',
    category: 'nutrition',
    target: 7,
  },
  {
    id: 'nutrition_hydration_30_days',
    nameEn: 'Hydration 30 Days',
    nameTh: 'ดื่มน้ำครบเป้า 30 วัน',
    description: 'Reach water goal in 30 different days',
    icon: '❤️',
    requirement: 'ทำเป้าดื่มน้ำครบ 8 แก้ว สะสม 30 วัน',
    category: 'nutrition',
    target: 30,
  },
];

export const mapDefinitionsToLockedBadges = (): Badge[] => {
  return BADGE_DEFINITIONS.map((definition) => ({
    id: definition.id,
    name: definition.nameEn,
    nameEn: definition.nameEn,
    nameTh: definition.nameTh,
    description: definition.description,
    icon: definition.icon,
    requirement: definition.requirement,
    progressCurrent: 0,
    progressTarget: definition.target,
  }));
};
