import { Fish, BiomeType, Rarity } from '@/types/fishing';

// ========================================
// FISH DATABASE - 100+ SPECIES
// ========================================

export const FISH_DATABASE: Fish[] = [
  // ========================================
  // 🌊 OCEAN (ทะเล) - 20 species
  // ========================================
  {
    id: 'ocean_sardine',
    name: 'Sardine',
    nameEn: 'Sardine',
    nameTh: 'ปลาซาร์ดีน',
    biome: 'ocean',
    rarity: 'common',
    minWeight: 0.1,
    maxWeight: 0.3,
    basePrice: 50,
    catchDifficulty: 1,
    spawnChance: 35,
    description: 'ปลาเล็กที่พบได้ทั่วไปในทะเล',
    emoji: '🐟',
  },
  {
    id: 'ocean_mackerel',
    name: 'Mackerel',
    nameEn: 'Mackerel',
    nameTh: 'ปลาทู',
    biome: 'ocean',
    rarity: 'common',
    minWeight: 0.3,
    maxWeight: 0.8,
    basePrice: 80,
    catchDifficulty: 2,
    spawnChance: 30,
    description: 'ปลาทะเลที่นิยมนำมาย่าง',
    emoji: '🐟',
  },
  {
    id: 'ocean_seabass',
    name: 'Sea Bass',
    nameEn: 'Sea Bass',
    nameTh: 'ปลากะพงขาว',
    biome: 'ocean',
    rarity: 'uncommon',
    minWeight: 1.0,
    maxWeight: 3.5,
    basePrice: 150,
    catchDifficulty: 4,
    spawnChance: 20,
    description: 'ปลากะพงขนาดใหญ่ เนื้อหนา',
    emoji: '🐠',
  },
  {
    id: 'ocean_grouper',
    name: 'Grouper',
    nameEn: 'Grouper',
    nameTh: 'ปลาเก๋า',
    biome: 'ocean',
    rarity: 'uncommon',
    minWeight: 2.0,
    maxWeight: 5.0,
    basePrice: 200,
    catchDifficulty: 5,
    spawnChance: 18,
    description: 'ปลาทะเลราคาดี เนื้อหวาน',
    emoji: '🐠',
  },
  {
    id: 'ocean_snapper',
    name: 'Red Snapper',
    nameEn: 'Red Snapper',
    nameTh: 'ปลากะพงแดง',
    biome: 'ocean',
    rarity: 'rare',
    minWeight: 2.5,
    maxWeight: 6.0,
    basePrice: 300,
    catchDifficulty: 6,
    spawnChance: 12,
    description: 'ปลาสีแดงสวยงาม เนื้อแน่น',
    emoji: '🐟',
  },
  {
    id: 'ocean_tuna',
    name: 'Yellowfin Tuna',
    nameEn: 'Yellowfin Tuna',
    nameTh: 'ปลาทูน่าครีบเหลือง',
    biome: 'ocean',
    rarity: 'rare',
    minWeight: 10.0,
    maxWeight: 30.0,
    basePrice: 400,
    catchDifficulty: 7,
    spawnChance: 10,
    description: 'ปลาทูน่าคุณภาพสูง ว่ายเร็ว',
    emoji: '🐟',
  },
  {
    id: 'ocean_mahi',
    name: 'Mahi Mahi',
    nameEn: 'Mahi Mahi',
    nameTh: 'ปลาดอลฟิน',
    biome: 'ocean',
    rarity: 'rare',
    minWeight: 5.0,
    maxWeight: 15.0,
    basePrice: 350,
    catchDifficulty: 6,
    spawnChance: 11,
    description: 'ปลาสีสันสวยงาม ชอบโดดน้ำ',
    emoji: '🐠',
  },
  {
    id: 'ocean_swordfish',
    name: 'Swordfish',
    nameEn: 'Swordfish',
    nameTh: 'ปลาดาบ',
    biome: 'ocean',
    rarity: 'epic',
    minWeight: 20.0,
    maxWeight: 50.0,
    basePrice: 600,
    catchDifficulty: 8,
    spawnChance: 6,
    description: 'ปลาตัวใหญ่มีงวงแหลมคล้ายดาบ',
    emoji: '🗡️',
  },
  {
    id: 'ocean_marlin',
    name: 'Blue Marlin',
    nameEn: 'Blue Marlin',
    nameTh: 'ปลามาร์ลินน้ำเงิน',
    biome: 'ocean',
    rarity: 'epic',
    minWeight: 30.0,
    maxWeight: 80.0,
    basePrice: 800,
    catchDifficulty: 9,
    spawnChance: 5,
    description: 'ปลาใหญ่ที่นักตกปลาฝันอยากได้',
    emoji: '🐋',
  },
  {
    id: 'ocean_shark',
    name: 'Tiger Shark',
    nameEn: 'Tiger Shark',
    nameTh: 'ฉลามเสือ',
    biome: 'ocean',
    rarity: 'epic',
    minWeight: 50.0,
    maxWeight: 150.0,
    basePrice: 900,
    catchDifficulty: 10,
    spawnChance: 4,
    description: 'ฉลามขนาดใหญ่ อันตราย',
    emoji: '🦈',
  },
  {
    id: 'ocean_whale_shark',
    name: 'Whale Shark',
    nameEn: 'Whale Shark',
    nameTh: 'ฉลามวาฬ',
    biome: 'ocean',
    rarity: 'legendary',
    minWeight: 200.0,
    maxWeight: 500.0,
    basePrice: 2000,
    catchDifficulty: 10,
    spawnChance: 1,
    description: 'ฉลามที่ใหญ่ที่สุดในโลก หายาก',
    emoji: '🐋',
  },
  {
    id: 'ocean_bluefin_tuna',
    name: 'Bluefin Tuna',
    nameEn: 'Bluefin Tuna',
    nameTh: 'ปลาทูน่าครีบน้ำเงิน',
    biome: 'ocean',
    rarity: 'legendary',
    minWeight: 100.0,
    maxWeight: 300.0,
    basePrice: 3000,
    catchDifficulty: 10,
    spawnChance: 1,
    description: 'ทูน่าที่หายากและแพงที่สุด',
    emoji: '🐟',
  },
  {
    id: 'ocean_barracuda',
    name: 'Barracuda',
    nameEn: 'Barracuda',
    nameTh: 'ปลาบาร์ราคูดา',
    biome: 'ocean',
    rarity: 'uncommon',
    minWeight: 3.0,
    maxWeight: 8.0,
    basePrice: 220,
    catchDifficulty: 5,
    spawnChance: 15,
    description: 'ปลาล่าเหยื่อที่ว่ายเร็ว',
    emoji: '🐟',
  },
  {
    id: 'ocean_squid',
    name: 'Giant Squid',
    nameEn: 'Giant Squid',
    nameTh: 'ปลาหมึกยักษ์',
    biome: 'ocean',
    rarity: 'rare',
    minWeight: 10.0,
    maxWeight: 25.0,
    basePrice: 380,
    catchDifficulty: 7,
    spawnChance: 9,
    description: 'หมึกขนาดใหญ่ มีหนวดยาว',
    emoji: '🦑',
  },
  {
    id: 'ocean_octopus',
    name: 'Giant Octopus',
    nameEn: 'Giant Octopus',
    nameTh: 'ปลาหมึกยักษ์แปดขา',
    biome: 'ocean',
    rarity: 'epic',
    minWeight: 15.0,
    maxWeight: 40.0,
    basePrice: 700,
    catchDifficulty: 8,
    spawnChance: 5,
    description: 'หมึกฉลาดและแข็งแรง',
    emoji: '🐙',
  },
  {
    id: 'ocean_crab',
    name: 'King Crab',
    nameEn: 'King Crab',
    nameTh: 'ปูยักษ์',
    biome: 'ocean',
    rarity: 'rare',
    minWeight: 5.0,
    maxWeight: 12.0,
    basePrice: 500,
    catchDifficulty: 6,
    spawnChance: 8,
    description: 'ปูขนาดใหญ่ เนื้อหวาน',
    emoji: '🦀',
  },
  {
    id: 'ocean_lobster',
    name: 'Lobster',
    nameEn: 'Lobster',
    nameTh: 'กุ้งมังกร',
    biome: 'ocean',
    rarity: 'rare',
    minWeight: 2.0,
    maxWeight: 6.0,
    basePrice: 600,
    catchDifficulty: 6,
    spawnChance: 7,
    description: 'กุ้งราคาแพง รสชาติดี',
    emoji: '🦞',
  },
  {
    id: 'ocean_stingray',
    name: 'Stingray',
    nameEn: 'Stingray',
    nameTh: 'ปลากระเบน',
    biome: 'ocean',
    rarity: 'uncommon',
    minWeight: 5.0,
    maxWeight: 15.0,
    basePrice: 180,
    catchDifficulty: 5,
    spawnChance: 16,
    description: 'ปลาแบนมีหางพิษ',
    emoji: '🐡',
  },
  {
    id: 'ocean_pufferfish',
    name: 'Pufferfish',
    nameEn: 'Pufferfish',
    nameTh: 'ปลาปักเป้า',
    biome: 'ocean',
    rarity: 'uncommon',
    minWeight: 0.5,
    maxWeight: 2.0,
    basePrice: 250,
    catchDifficulty: 4,
    spawnChance: 14,
    description: 'ปลาพองตัวได้ มีพิษ',
    emoji: '🐡',
  },
  {
    id: 'ocean_anglerfish',
    name: 'Anglerfish',
    nameEn: 'Anglerfish',
    nameTh: 'ปลาเจ้าหน้าที่',
    biome: 'ocean',
    rarity: 'epic',
    minWeight: 8.0,
    maxWeight: 20.0,
    basePrice: 750,
    catchDifficulty: 8,
    spawnChance: 4,
    description: 'ปลาลึกมีไฟล่อเหยื่อ',
    emoji: '🐟',
  },

  // ========================================
  // 🏞️ RIVER (แม่น้ำ) - 18 species
  // ========================================
  {
    id: 'river_carp',
    name: 'Common Carp',
    nameEn: 'Common Carp',
    nameTh: 'ปลาคาร์พ',
    biome: 'river',
    rarity: 'common',
    minWeight: 1.0,
    maxWeight: 5.0,
    basePrice: 60,
    catchDifficulty: 2,
    spawnChance: 35,
    description: 'ปลาน้ำจืดพบได้ทั่วไป',
    emoji: '🐟',
  },
  {
    id: 'river_catfish',
    name: 'Catfish',
    nameEn: 'Catfish',
    nameTh: 'ปลาดุก',
    biome: 'river',
    rarity: 'common',
    minWeight: 2.0,
    maxWeight: 8.0,
    basePrice: 70,
    catchDifficulty: 3,
    spawnChance: 30,
    description: 'ปลามีหนวดยาว อาศัยใต้น้ำ',
    emoji: '🐟',
  },
  {
    id: 'river_tilapia',
    name: 'Tilapia',
    nameEn: 'Tilapia',
    nameTh: 'ปลานิล',
    biome: 'river',
    rarity: 'common',
    minWeight: 0.5,
    maxWeight: 2.0,
    basePrice: 50,
    catchDifficulty: 1,
    spawnChance: 32,
    description: 'ปลาเลี้ยงง่าย รสชาติดี',
    emoji: '🐟',
  },
  {
    id: 'river_bass',
    name: 'Largemouth Bass',
    nameEn: 'Largemouth Bass',
    nameTh: 'ปลาเบสปากใหญ่',
    biome: 'river',
    rarity: 'uncommon',
    minWeight: 2.0,
    maxWeight: 7.0,
    basePrice: 150,
    catchDifficulty: 4,
    spawnChance: 20,
    description: 'ปลาล่าเหยื่อ ชอบซ่อนตัว',
    emoji: '🐠',
  },
  {
    id: 'river_pike',
    name: 'Northern Pike',
    nameEn: 'Northern Pike',
    nameTh: 'ปลาไพค์',
    biome: 'river',
    rarity: 'uncommon',
    minWeight: 3.0,
    maxWeight: 10.0,
    basePrice: 180,
    catchDifficulty: 5,
    spawnChance: 18,
    description: 'ปลาดุร้ายมีฟันแหลม',
    emoji: '🐟',
  },
  {
    id: 'river_trout',
    name: 'Rainbow Trout',
    nameEn: 'Rainbow Trout',
    nameTh: 'ปลาเทราต์สายรุ้ง',
    biome: 'river',
    rarity: 'rare',
    minWeight: 1.0,
    maxWeight: 4.0,
    basePrice: 250,
    catchDifficulty: 5,
    spawnChance: 12,
    description: 'ปลาสวยงามมีสีสัน',
    emoji: '🐟',
  },
  {
    id: 'river_salmon',
    name: 'Atlantic Salmon',
    nameEn: 'Atlantic Salmon',
    nameTh: 'ปลาแซลมอน',
    biome: 'river',
    rarity: 'rare',
    minWeight: 5.0,
    maxWeight: 15.0,
    basePrice: 400,
    catchDifficulty: 7,
    spawnChance: 10,
    description: 'ปลาโยกย้ายถิ่นเพื่อวางไข่',
    emoji: '🐟',
  },
  {
    id: 'river_sturgeon',
    name: 'Sturgeon',
    nameEn: 'Sturgeon',
    nameTh: 'ปลาสเตอร์เจียน',
    biome: 'river',
    rarity: 'epic',
    minWeight: 20.0,
    maxWeight: 100.0,
    basePrice: 800,
    catchDifficulty: 9,
    spawnChance: 5,
    description: 'ปลาโบราณมีอายุยืน',
    emoji: '🐟',
  },
  {
    id: 'river_arapaima',
    name: 'Arapaima',
    nameEn: 'Arapaima',
    nameTh: 'ปลาอารพายมา',
    biome: 'river',
    rarity: 'legendary',
    minWeight: 50.0,
    maxWeight: 200.0,
    basePrice: 2500,
    catchDifficulty: 10,
    spawnChance: 1,
    description: 'ปลาน้ำจืดที่ใหญ่ที่สุด',
    emoji: '🐋',
  },
  {
    id: 'river_alligator_gar',
    name: 'Alligator Gar',
    nameEn: 'Alligator Gar',
    nameTh: 'ปลากระเบนจระเข้',
    biome: 'river',
    rarity: 'epic',
    minWeight: 30.0,
    maxWeight: 80.0,
    basePrice: 700,
    catchDifficulty: 8,
    spawnChance: 4,
    description: 'ปลาดุร้ายคล้ายจระเข้',
    emoji: '🐊',
  },
  {
    id: 'river_snakehead',
    name: 'Giant Snakehead',
    nameEn: 'Giant Snakehead',
    nameTh: 'ปลาชะโดยักษ์',
    biome: 'river',
    rarity: 'rare',
    minWeight: 5.0,
    maxWeight: 15.0,
    basePrice: 300,
    catchDifficulty: 6,
    spawnChance: 11,
    description: 'ปลาดุร้ายหายใจได้ในอากาศ',
    emoji: '🐍',
  },
  {
    id: 'river_perch',
    name: 'Yellow Perch',
    nameEn: 'Yellow Perch',
    nameTh: 'ปลาเพิร์ช',
    biome: 'river',
    rarity: 'common',
    minWeight: 0.3,
    maxWeight: 1.5,
    basePrice: 80,
    catchDifficulty: 2,
    spawnChance: 28,
    description: 'ปลาเล็กมีลายเหลือง',
    emoji: '🐟',
  },
  {
    id: 'river_eel',
    name: 'River Eel',
    nameEn: 'River Eel',
    nameTh: 'ปลาไหล',
    biome: 'river',
    rarity: 'uncommon',
    minWeight: 1.0,
    maxWeight: 5.0,
    basePrice: 200,
    catchDifficulty: 6,
    spawnChance: 15,
    description: 'ปลาลื่นจับยาก',
    emoji: '🐍',
  },
  {
    id: 'river_paddlefish',
    name: 'Paddlefish',
    nameEn: 'Paddlefish',
    nameTh: 'ปลาจงอยยาว',
    biome: 'river',
    rarity: 'rare',
    minWeight: 10.0,
    maxWeight: 30.0,
    basePrice: 450,
    catchDifficulty: 7,
    spawnChance: 9,
    description: 'ปลามีจงอยยาวประหลาด',
    emoji: '🐟',
  },
  {
    id: 'river_muskellunge',
    name: 'Muskellunge',
    nameEn: 'Muskellunge',
    nameTh: 'ปลามัสกี้',
    biome: 'river',
    rarity: 'epic',
    minWeight: 15.0,
    maxWeight: 35.0,
    basePrice: 650,
    catchDifficulty: 8,
    spawnChance: 6,
    description: 'ปลาล่าเหยื่อตัวใหญ่',
    emoji: '🐟',
  },
  {
    id: 'river_walleye',
    name: 'Walleye',
    nameEn: 'Walleye',
    nameTh: 'ปลาวาลอาย',
    biome: 'river',
    rarity: 'uncommon',
    minWeight: 2.0,
    maxWeight: 6.0,
    basePrice: 170,
    catchDifficulty: 4,
    spawnChance: 19,
    description: 'ปลาตามองเห็นในที่มืด',
    emoji: '🐟',
  },
  {
    id: 'river_zander',
    name: 'Zander',
    nameEn: 'Zander',
    nameTh: 'ปลาแซนเดอร์',
    biome: 'river',
    rarity: 'rare',
    minWeight: 3.0,
    maxWeight: 10.0,
    basePrice: 320,
    catchDifficulty: 6,
    spawnChance: 10,
    description: 'ปลาล่าเหยื่อยามค่ำคืน',
    emoji: '🐟',
  },
  {
    id: 'river_taimen',
    name: 'Taimen',
    nameEn: 'Taimen',
    nameTh: 'ปลาไทเมน',
    biome: 'river',
    rarity: 'legendary',
    minWeight: 30.0,
    maxWeight: 60.0,
    basePrice: 1800,
    catchDifficulty: 10,
    spawnChance: 2,
    description: 'ปลาเทราต์ยักษ์หายาก',
    emoji: '🐟',
  },

  // ========================================
  // 🏔️ LAKE (ทะเลสาบ) - 18 species
  // ========================================
  {
    id: 'lake_bluegill',
    name: 'Bluegill',
    nameEn: 'Bluegill',
    nameTh: 'ปลาบลูกิล',
    biome: 'lake',
    rarity: 'common',
    minWeight: 0.2,
    maxWeight: 1.0,
    basePrice: 40,
    catchDifficulty: 1,
    spawnChance: 35,
    description: 'ปลาเล็กสีสันสวย',
    emoji: '🐟',
  },
  {
    id: 'lake_crappie',
    name: 'Crappie',
    nameEn: 'Crappie',
    nameTh: 'ปลาแครปปี้',
    biome: 'lake',
    rarity: 'common',
    minWeight: 0.3,
    maxWeight: 1.5,
    basePrice: 60,
    catchDifficulty: 2,
    spawnChance: 32,
    description: 'ปลาขนาดเล็กถึงกลาง',
    emoji: '🐟',
  },
  {
    id: 'lake_sunfish',
    name: 'Sunfish',
    nameEn: 'Sunfish',
    nameTh: 'ปลาซันฟิช',
    biome: 'lake',
    rarity: 'common',
    minWeight: 0.2,
    maxWeight: 0.8,
    basePrice: 50,
    catchDifficulty: 1,
    spawnChance: 33,
    description: 'ปลาสีสดใสชอบแสงแดด',
    emoji: '🐠',
  },
  {
    id: 'lake_smallmouth_bass',
    name: 'Smallmouth Bass',
    nameEn: 'Smallmouth Bass',
    nameTh: 'ปลาเบสปากเล็ก',
    biome: 'lake',
    rarity: 'uncommon',
    minWeight: 1.5,
    maxWeight: 5.0,
    basePrice: 140,
    catchDifficulty: 4,
    spawnChance: 22,
    description: 'ปลาสู้ดี ชอบน้ำเย็น',
    emoji: '🐟',
  },
  {
    id: 'lake_pickerel',
    name: 'Chain Pickerel',
    nameEn: 'Chain Pickerel',
    nameTh: 'ปลาพิคเคอเรล',
    biome: 'lake',
    rarity: 'uncommon',
    minWeight: 1.0,
    maxWeight: 4.0,
    basePrice: 130,
    catchDifficulty: 3,
    spawnChance: 20,
    description: 'ปลาล่าเหยื่อว่องไว',
    emoji: '🐟',
  },
  {
    id: 'lake_lake_trout',
    name: 'Lake Trout',
    nameEn: 'Lake Trout',
    nameTh: 'ปลาเทราต์ทะเลสาบ',
    biome: 'lake',
    rarity: 'rare',
    minWeight: 3.0,
    maxWeight: 15.0,
    basePrice: 280,
    catchDifficulty: 6,
    spawnChance: 12,
    description: 'ปลาอาศัยน้ำเย็นลึก',
    emoji: '🐟',
  },
  {
    id: 'lake_kokanee',
    name: 'Kokanee Salmon',
    nameEn: 'Kokanee Salmon',
    nameTh: 'แซลมอนโคคานีน',
    biome: 'lake',
    rarity: 'rare',
    minWeight: 1.0,
    maxWeight: 3.5,
    basePrice: 220,
    catchDifficulty: 5,
    spawnChance: 10,
    description: 'แซลมอนที่อาศัยในทะเลสาบ',
    emoji: '🐟',
  },
  {
    id: 'lake_white_bass',
    name: 'White Bass',
    nameEn: 'White Bass',
    nameTh: 'ปลาเบสขาว',
    biome: 'lake',
    rarity: 'uncommon',
    minWeight: 0.8,
    maxWeight: 3.0,
    basePrice: 110,
    catchDifficulty: 3,
    spawnChance: 24,
    description: 'ปลาฝูงใหญ่ว่ายเร็ว',
    emoji: '🐟',
  },
  {
    id: 'lake_bowfin',
    name: 'Bowfin',
    nameEn: 'Bowfin',
    nameTh: 'ปลาโบว์ฟิน',
    biome: 'lake',
    rarity: 'rare',
    minWeight: 3.0,
    maxWeight: 8.0,
    basePrice: 300,
    catchDifficulty: 6,
    spawnChance: 9,
    description: 'ปลาโบราณหายใจได้ในอากาศ',
    emoji: '🐟',
  },
  {
    id: 'lake_char',
    name: 'Arctic Char',
    nameEn: 'Arctic Char',
    nameTh: 'ปลาชาร์อาร์กติก',
    biome: 'lake',
    rarity: 'rare',
    minWeight: 2.0,
    maxWeight: 8.0,
    basePrice: 350,
    catchDifficulty: 6,
    spawnChance: 8,
    description: 'ปลาน้ำเย็นสีสวยงาม',
    emoji: '🐟',
  },
  {
    id: 'lake_muskie',
    name: 'Tiger Muskie',
    nameEn: 'Tiger Muskie',
    nameTh: 'มัสกี้ลายเสือ',
    biome: 'lake',
    rarity: 'epic',
    minWeight: 10.0,
    maxWeight: 25.0,
    basePrice: 600,
    catchDifficulty: 8,
    spawnChance: 5,
    description: 'ปลาผสมพันธุ์หายาก',
    emoji: '🐟',
  },
  {
    id: 'lake_splake',
    name: 'Splake',
    nameEn: 'Splake',
    nameTh: 'สปลาก',
    biome: 'lake',
    rarity: 'uncommon',
    minWeight: 1.5,
    maxWeight: 5.0,
    basePrice: 160,
    catchDifficulty: 4,
    spawnChance: 18,
    description: 'ลูกผสมของเทราต์ 2 สายพันธุ์',
    emoji: '🐟',
  },
  {
    id: 'lake_burbot',
    name: 'Burbot',
    nameEn: 'Burbot',
    nameTh: 'เบอร์บอต',
    biome: 'lake',
    rarity: 'rare',
    minWeight: 2.0,
    maxWeight: 6.0,
    basePrice: 260,
    catchDifficulty: 5,
    spawnChance: 11,
    description: 'ปลาน้ำเย็นตระกูลค็อด',
    emoji: '🐟',
  },
  {
    id: 'lake_trophy_bass',
    name: 'Trophy Bass',
    nameEn: 'Trophy Bass',
    nameTh: 'เบสโทรฟี่',
    biome: 'lake',
    rarity: 'epic',
    minWeight: 8.0,
    maxWeight: 12.0,
    basePrice: 700,
    catchDifficulty: 9,
    spawnChance: 4,
    description: 'เบสขนาดใหญ่สุด',
    emoji: '🏆',
  },
  {
    id: 'lake_golden_trout',
    name: 'Golden Trout',
    nameEn: 'Golden Trout',
    nameTh: 'เทราต์ทอง',
    biome: 'lake',
    rarity: 'legendary',
    minWeight: 2.0,
    maxWeight: 5.0,
    basePrice: 1500,
    catchDifficulty: 10,
    spawnChance: 2,
    description: 'เทราต์สีทองหายากมาก',
    emoji: '✨',
  },
  {
    id: 'lake_giant_carp',
    name: 'Giant Mirror Carp',
    nameEn: 'Giant Mirror Carp',
    nameTh: 'คาร์พกระจกยักษ์',
    biome: 'lake',
    rarity: 'epic',
    minWeight: 15.0,
    maxWeight: 40.0,
    basePrice: 550,
    catchDifficulty: 7,
    spawnChance: 6,
    description: 'คาร์พขนาดใหญ่มีเกล็ดน้อย',
    emoji: '🐟',
  },
  {
    id: 'lake_grass_carp',
    name: 'Grass Carp',
    nameEn: 'Grass Carp',
    nameTh: 'ปลาหมอจีน',
    biome: 'lake',
    rarity: 'common',
    minWeight: 3.0,
    maxWeight: 10.0,
    basePrice: 70,
    catchDifficulty: 3,
    spawnChance: 26,
    description: 'ปลากินพืชขนาดใหญ่',
    emoji: '🐟',
  },
  {
    id: 'lake_buffalo_fish',
    name: 'Bigmouth Buffalo',
    nameEn: 'Bigmouth Buffalo',
    nameTh: 'บัฟฟาโลปากใหญ่',
    biome: 'lake',
    rarity: 'uncommon',
    minWeight: 5.0,
    maxWeight: 15.0,
    basePrice: 150,
    catchDifficulty: 5,
    spawnChance: 16,
    description: 'ปลาอเมริกาขนาดใหญ่',
    emoji: '🐟',
  },

  // ========================================
  // ❄️ ICE (น้ำแข็ง) - 16 species
  // ========================================
  {
    id: 'ice_perch',
    name: 'Ice Perch',
    nameEn: 'Ice Perch',
    nameTh: 'เพิร์ชน้ำแข็ง',
    biome: 'ice',
    rarity: 'common',
    minWeight: 0.3,
    maxWeight: 1.2,
    basePrice: 90,
    catchDifficulty: 2,
    spawnChance: 35,
    description: 'ปลาขนาดเล็กทนความเย็น',
    emoji: '🐟',
  },
  {
    id: 'ice_whitefish',
    name: 'Whitefish',
    nameEn: 'Whitefish',
    nameTh: 'ปลาไวท์ฟิช',
    biome: 'ice',
    rarity: 'common',
    minWeight: 1.0,
    maxWeight: 3.0,
    basePrice: 100,
    catchDifficulty: 2,
    spawnChance: 32,
    description: 'ปลาน้ำเย็นเนื้อขาว',
    emoji: '🐟',
  },
  {
    id: 'ice_cisco',
    name: 'Cisco',
    nameEn: 'Cisco',
    nameTh: 'ซิสโก้',
    biome: 'ice',
    rarity: 'common',
    minWeight: 0.5,
    maxWeight: 2.0,
    basePrice: 80,
    catchDifficulty: 1,
    spawnChance: 30,
    description: 'ปลาน้ำเย็นฝูงใหญ่',
    emoji: '🐟',
  },
  {
    id: 'ice_brook_trout',
    name: 'Brook Trout',
    nameEn: 'Brook Trout',
    nameTh: 'เทราต์ลำธาร',
    biome: 'ice',
    rarity: 'uncommon',
    minWeight: 0.8,
    maxWeight: 3.0,
    basePrice: 180,
    catchDifficulty: 4,
    spawnChance: 22,
    description: 'เทราต์สีสันสวยงาม',
    emoji: '🐟',
  },
  {
    id: 'ice_northern_pike',
    name: 'Ice Pike',
    nameEn: 'Ice Pike',
    nameTh: 'ไพค์น้ำแข็ง',
    biome: 'ice',
    rarity: 'uncommon',
    minWeight: 3.0,
    maxWeight: 8.0,
    basePrice: 200,
    catchDifficulty: 5,
    spawnChance: 18,
    description: 'ไพค์ที่ชอบน้ำเย็นจัด',
    emoji: '🐟',
  },
  {
    id: 'ice_walleye',
    name: 'Ice Walleye',
    nameEn: 'Ice Walleye',
    nameTh: 'วาลอายน้ำแข็ง',
    biome: 'ice',
    rarity: 'rare',
    minWeight: 2.0,
    maxWeight: 7.0,
    basePrice: 250,
    catchDifficulty: 6,
    spawnChance: 14,
    description: 'วาลอายที่ใหญ่กว่าปกติ',
    emoji: '🐟',
  },
  {
    id: 'ice_lake_trout',
    name: 'Arctic Lake Trout',
    nameEn: 'Arctic Lake Trout',
    nameTh: 'เทราต์ทะเลสาบอาร์กติก',
    biome: 'ice',
    rarity: 'rare',
    minWeight: 5.0,
    maxWeight: 20.0,
    basePrice: 400,
    catchDifficulty: 7,
    spawnChance: 10,
    description: 'เทราต์ทนหนาวที่สุด',
    emoji: '🐟',
  },
  {
    id: 'ice_burbot',
    name: 'Arctic Burbot',
    nameEn: 'Arctic Burbot',
    nameTh: 'เบอร์บอตอาร์กติก',
    biome: 'ice',
    rarity: 'rare',
    minWeight: 3.0,
    maxWeight: 10.0,
    basePrice: 320,
    catchDifficulty: 6,
    spawnChance: 12,
    description: 'ปลาใต้น้ำแข็งหายาก',
    emoji: '🐟',
  },
  {
    id: 'ice_arctic_char',
    name: 'Arctic Char',
    nameEn: 'Arctic Char',
    nameTh: 'ชาร์อาร์กติก',
    biome: 'ice',
    rarity: 'rare',
    minWeight: 3.0,
    maxWeight: 12.0,
    basePrice: 380,
    catchDifficulty: 7,
    spawnChance: 9,
    description: 'ปลาสีสดใสท่ามกลางหิมะ',
    emoji: '🐟',
  },
  {
    id: 'ice_grayling',
    name: 'Arctic Grayling',
    nameEn: 'Arctic Grayling',
    nameTh: 'เกรย์ลิงอาร์กติก',
    biome: 'ice',
    rarity: 'uncommon',
    minWeight: 0.5,
    maxWeight: 2.5,
    basePrice: 150,
    catchDifficulty: 4,
    spawnChance: 20,
    description: 'ปลามีครีบหลังสูง',
    emoji: '🐟',
  },
  {
    id: 'ice_giant_pike',
    name: 'Ice Giant Pike',
    nameEn: 'Ice Giant Pike',
    nameTh: 'ไพค์ยักษ์น้ำแข็ง',
    biome: 'ice',
    rarity: 'epic',
    minWeight: 15.0,
    maxWeight: 30.0,
    basePrice: 700,
    catchDifficulty: 9,
    spawnChance: 5,
    description: 'ไพค์ที่ใหญ่ที่สุด',
    emoji: '🐟',
  },
  {
    id: 'ice_monster_trout',
    name: 'Monster Trout',
    nameEn: 'Monster Trout',
    nameTh: 'เทราต์มอนสเตอร์',
    biome: 'ice',
    rarity: 'epic',
    minWeight: 20.0,
    maxWeight: 40.0,
    basePrice: 850,
    catchDifficulty: 9,
    spawnChance: 4,
    description: 'เทราต์ยักษ์หายาก',
    emoji: '🐟',
  },
  {
    id: 'ice_glacier_fish',
    name: 'Glacier Fish',
    nameEn: 'Glacier Fish',
    nameTh: 'ปลาธารน้ำแข็ง',
    biome: 'ice',
    rarity: 'legendary',
    minWeight: 10.0,
    maxWeight: 25.0,
    basePrice: 2000,
    catchDifficulty: 10,
    spawnChance: 2,
    description: 'ปลาในตำนานใต้น้ำแข็งหนา',
    emoji: '❄️',
  },
  {
    id: 'ice_frost_salmon',
    name: 'Frost Salmon',
    nameEn: 'Frost Salmon',
    nameTh: 'แซลมอนน้ำแข็ง',
    biome: 'ice',
    rarity: 'epic',
    minWeight: 8.0,
    maxWeight: 20.0,
    basePrice: 650,
    catchDifficulty: 8,
    spawnChance: 6,
    description: 'แซลมอนสีขาวราวน้ำแข็ง',
    emoji: '🐟',
  },
  {
    id: 'ice_crystal_carp',
    name: 'Crystal Carp',
    nameEn: 'Crystal Carp',
    nameTh: 'คาร์พคริสตัล',
    biome: 'ice',
    rarity: 'legendary',
    minWeight: 15.0,
    maxWeight: 35.0,
    basePrice: 1800,
    catchDifficulty: 10,
    spawnChance: 1,
    description: 'คาร์พใสดังคริสตัล',
    emoji: '💎',
  },
  {
    id: 'ice_snowflake_fish',
    name: 'Snowflake Fish',
    nameEn: 'Snowflake Fish',
    nameTh: 'ปลาเกล็ดหิมะ',
    biome: 'ice',
    rarity: 'legendary',
    minWeight: 5.0,
    maxWeight: 15.0,
    basePrice: 2200,
    catchDifficulty: 10,
    spawnChance: 1,
    description: 'ปลาหายากเกล็ดเหมือนเกล็ดหิมะ',
    emoji: '❄️',
  },

  // ========================================
  // 💧 POND (บ่อ) - 16 species
  // ========================================
  {
    id: 'pond_goldfish',
    name: 'Goldfish',
    nameEn: 'Goldfish',
    nameTh: 'ปลาทอง',
    biome: 'pond',
    rarity: 'common',
    minWeight: 0.1,
    maxWeight: 0.5,
    basePrice: 30,
    catchDifficulty: 1,
    spawnChance: 40,
    description: 'ปลาสวยงามเลี้ยงง่าย',
    emoji: '🐠',
  },
  {
    id: 'pond_koi',
    name: 'Koi',
    nameEn: 'Koi',
    nameTh: 'ปลาคาร์พญี่ปุ่น',
    biome: 'pond',
    rarity: 'uncommon',
    minWeight: 1.0,
    maxWeight: 5.0,
    basePrice: 200,
    catchDifficulty: 3,
    spawnChance: 20,
    description: 'ปลาคาร์พสวยงามราคาแพง',
    emoji: '🐠',
  },
  {
    id: 'pond_fancy_goldfish',
    name: 'Fancy Goldfish',
    nameEn: 'Fancy Goldfish',
    nameTh: 'ปลาทองหางยาว',
    biome: 'pond',
    rarity: 'uncommon',
    minWeight: 0.3,
    maxWeight: 1.0,
    basePrice: 120,
    catchDifficulty: 2,
    spawnChance: 25,
    description: 'ปลาทองพันธุ์แต่ง',
    emoji: '🐠',
  },
  {
    id: 'pond_turtle',
    name: 'Pond Turtle',
    nameEn: 'Pond Turtle',
    nameTh: 'เต่าบ่อ',
    biome: 'pond',
    rarity: 'common',
    minWeight: 0.5,
    maxWeight: 2.0,
    basePrice: 50,
    catchDifficulty: 2,
    spawnChance: 28,
    description: 'เต่าขนาดเล็กอาบแดด',
    emoji: '🐢',
  },
  {
    id: 'pond_betta',
    name: 'Giant Betta',
    nameEn: 'Giant Betta',
    nameTh: 'ปลากัดยักษ์',
    biome: 'pond',
    rarity: 'rare',
    minWeight: 0.2,
    maxWeight: 0.5,
    basePrice: 300,
    catchDifficulty: 4,
    spawnChance: 12,
    description: 'ปลากัดขนาดใหญ่สวยงาม',
    emoji: '🐠',
  },
  {
    id: 'pond_catfish_small',
    name: 'Channel Catfish',
    nameEn: 'Channel Catfish',
    nameTh: 'ปลาดุกช่อง',
    biome: 'pond',
    rarity: 'common',
    minWeight: 1.0,
    maxWeight: 4.0,
    basePrice: 60,
    catchDifficulty: 2,
    spawnChance: 30,
    description: 'ปลาดุกขนาดกลาง',
    emoji: '🐟',
  },
  {
    id: 'pond_bass_farm',
    name: 'Farm Bass',
    nameEn: 'Farm Bass',
    nameTh: 'เบสฟาร์ม',
    biome: 'pond',
    rarity: 'uncommon',
    minWeight: 1.5,
    maxWeight: 4.0,
    basePrice: 130,
    catchDifficulty: 3,
    spawnChance: 22,
    description: 'เบสที่เลี้ยงในบ่อ',
    emoji: '🐟',
  },
  {
    id: 'pond_giant_koi',
    name: 'Giant Koi',
    nameEn: 'Giant Koi',
    nameTh: 'คาร์พญี่ปุ่นยักษ์',
    biome: 'pond',
    rarity: 'rare',
    minWeight: 8.0,
    maxWeight: 20.0,
    basePrice: 500,
    catchDifficulty: 7,
    spawnChance: 8,
    description: 'คาร์พขนาดใหญ่หายาก',
    emoji: '🐠',
  },
  {
    id: 'pond_arowana',
    name: 'Arowana',
    nameEn: 'Arowana',
    nameTh: 'ปลามังกร',
    biome: 'pond',
    rarity: 'epic',
    minWeight: 3.0,
    maxWeight: 10.0,
    basePrice: 800,
    catchDifficulty: 8,
    spawnChance: 5,
    description: 'ปลามงคลราคาแพง',
    emoji: '🐉',
  },
  {
    id: 'pond_platinum_arowana',
    name: 'Platinum Arowana',
    nameEn: 'Platinum Arowana',
    nameTh: 'ปลามังกรแพลทินัม',
    biome: 'pond',
    rarity: 'legendary',
    minWeight: 5.0,
    maxWeight: 12.0,
    basePrice: 3000,
    catchDifficulty: 10,
    spawnChance: 1,
    description: 'ปลามังกรหายากที่สุด',
    emoji: '✨',
  },
  {
    id: 'pond_butterfly_koi',
    name: 'Butterfly Koi',
    nameEn: 'Butterfly Koi',
    nameTh: 'คาร์พญี่ปุ่นหางผีเสื้อ',
    biome: 'pond',
    rarity: 'rare',
    minWeight: 2.0,
    maxWeight: 6.0,
    basePrice: 350,
    catchDifficulty: 5,
    spawnChance: 10,
    description: 'คาร์พครีบยาวสวยงาม',
    emoji: '🦋',
  },
  {
    id: 'pond_ghost_koi',
    name: 'Ghost Koi',
    nameEn: 'Ghost Koi',
    nameTh: 'คาร์พผี',
    biome: 'pond',
    rarity: 'rare',
    minWeight: 3.0,
    maxWeight: 8.0,
    basePrice: 400,
    catchDifficulty: 6,
    spawnChance: 9,
    description: 'คาร์พสีขาวโปร่งแสง',
    emoji: '👻',
  },
  {
    id: 'pond_gourami_giant',
    name: 'Giant Gourami',
    nameEn: 'Giant Gourami',
    nameTh: 'ปลาหมอยักษ์',
    biome: 'pond',
    rarity: 'uncommon',
    minWeight: 2.0,
    maxWeight: 7.0,
    basePrice: 140,
    catchDifficulty: 4,
    spawnChance: 18,
    description: 'ปลาหมอขนาดใหญ่',
    emoji: '🐟',
  },
  {
    id: 'pond_oscar',
    name: 'Tiger Oscar',
    nameEn: 'Tiger Oscar',
    nameTh: 'ออสการ์',
    biome: 'pond',
    rarity: 'uncommon',
    minWeight: 1.0,
    maxWeight: 3.5,
    basePrice: 150,
    catchDifficulty: 3,
    spawnChance: 16,
    description: 'ปลาสวยงามมีนิสัยดุ',
    emoji: '🐠',
  },
  {
    id: 'pond_pacu',
    name: 'Red Pacu',
    nameEn: 'Red Pacu',
    nameTh: 'ปาคูแดง',
    biome: 'pond',
    rarity: 'rare',
    minWeight: 5.0,
    maxWeight: 15.0,
    basePrice: 280,
    catchDifficulty: 6,
    spawnChance: 11,
    description: 'ปลาขนาดใหญ่กินพืช',
    emoji: '🐟',
  },
  {
    id: 'pond_albino_catfish',
    name: 'Albino Catfish',
    nameEn: 'Albino Catfish',
    nameTh: 'ปลาดุกอัลไบโน',
    biome: 'pond',
    rarity: 'epic',
    minWeight: 10.0,
    maxWeight: 25.0,
    basePrice: 600,
    catchDifficulty: 7,
    spawnChance: 6,
    description: 'ปลาดุกสีขาวหายาก',
    emoji: '⚪',
  },

  // ========================================
  // 🌿 SWAMP (บึง) - 18 species
  // ========================================
  {
    id: 'swamp_mudfish',
    name: 'Mudfish',
    nameEn: 'Mudfish',
    nameTh: 'ปลาโคลน',
    biome: 'swamp',
    rarity: 'common',
    minWeight: 0.3,
    maxWeight: 1.0,
    basePrice: 40,
    catchDifficulty: 1,
    spawnChance: 36,
    description: 'ปลาอาศัยในโคลน',
    emoji: '🐟',
  },
  {
    id: 'swamp_bullhead',
    name: 'Brown Bullhead',
    nameEn: 'Brown Bullhead',
    nameTh: 'ปลาดุกบึง',
    biome: 'swamp',
    rarity: 'common',
    minWeight: 0.5,
    maxWeight: 2.0,
    basePrice: 50,
    catchDifficulty: 2,
    spawnChance: 33,
    description: 'ปลาดุกทนสภาพน้ำเสีย',
    emoji: '🐟',
  },
  {
    id: 'swamp_bowfin',
    name: 'Swamp Bowfin',
    nameEn: 'Swamp Bowfin',
    nameTh: 'โบว์ฟินบึง',
    biome: 'swamp',
    rarity: 'uncommon',
    minWeight: 2.0,
    maxWeight: 6.0,
    basePrice: 130,
    catchDifficulty: 4,
    spawnChance: 22,
    description: 'ปลาทนทานต่อน้ำขาดออกซิเจน',
    emoji: '🐟',
  },
  {
    id: 'swamp_gar',
    name: 'Longnose Gar',
    nameEn: 'Longnose Gar',
    nameTh: 'การ์จงอยยาว',
    biome: 'swamp',
    rarity: 'uncommon',
    minWeight: 3.0,
    maxWeight: 8.0,
    basePrice: 150,
    catchDifficulty: 5,
    spawnChance: 20,
    description: 'ปลาจงอยยาวคล้ายจระเข้',
    emoji: '🐊',
  },
  {
    id: 'swamp_snakehead',
    name: 'Swamp Snakehead',
    nameEn: 'Swamp Snakehead',
    nameTh: 'ปลาชะโดบึง',
    biome: 'swamp',
    rarity: 'rare',
    minWeight: 3.0,
    maxWeight: 10.0,
    basePrice: 220,
    catchDifficulty: 6,
    spawnChance: 14,
    description: 'ชะโดขนาดใหญ่ในบึง',
    emoji: '🐍',
  },
  {
    id: 'swamp_alligator_gar',
    name: 'Swamp Alligator Gar',
    nameEn: 'Swamp Alligator Gar',
    nameTh: 'การ์จระเข้บึง',
    biome: 'swamp',
    rarity: 'rare',
    minWeight: 15.0,
    maxWeight: 40.0,
    basePrice: 400,
    catchDifficulty: 7,
    spawnChance: 10,
    description: 'การ์ยักษ์ในบึงลึก',
    emoji: '🐊',
  },
  {
    id: 'swamp_lungfish',
    name: 'Lungfish',
    nameEn: 'Lungfish',
    nameTh: 'ปลาปอด',
    biome: 'swamp',
    rarity: 'rare',
    minWeight: 2.0,
    maxWeight: 6.0,
    basePrice: 300,
    catchDifficulty: 5,
    spawnChance: 12,
    description: 'ปลาโบราณหายใจได้นอกน้ำ',
    emoji: '🫁',
  },
  {
    id: 'swamp_giant_snakehead',
    name: 'Giant Swamp Snakehead',
    nameEn: 'Giant Swamp Snakehead',
    nameTh: 'ชะโดบึงยักษ์',
    biome: 'swamp',
    rarity: 'epic',
    minWeight: 12.0,
    maxWeight: 25.0,
    basePrice: 600,
    catchDifficulty: 8,
    spawnChance: 6,
    description: 'ชะโดที่ใหญ่ที่สุด',
    emoji: '🐍',
  },
  {
    id: 'swamp_monster_gar',
    name: 'Monster Gar',
    nameEn: 'Monster Gar',
    nameTh: 'การ์มอนสเตอร์',
    biome: 'swamp',
    rarity: 'epic',
    minWeight: 50.0,
    maxWeight: 120.0,
    basePrice: 900,
    catchDifficulty: 9,
    spawnChance: 4,
    description: 'การ์ขนาดใหญ่สุดในบึง',
    emoji: '🐊',
  },
  {
    id: 'swamp_arapaima',
    name: 'Swamp Arapaima',
    nameEn: 'Swamp Arapaima',
    nameTh: 'อารพายมาบึง',
    biome: 'swamp',
    rarity: 'legendary',
    minWeight: 80.0,
    maxWeight: 200.0,
    basePrice: 2500,
    catchDifficulty: 10,
    spawnChance: 2,
    description: 'ปลายักษ์ในบึงลึก',
    emoji: '🐋',
  },
  {
    id: 'swamp_prehistoric_gar',
    name: 'Prehistoric Gar',
    nameEn: 'Prehistoric Gar',
    nameTh: 'การ์ก่อนประวัติศาสตร์',
    biome: 'swamp',
    rarity: 'legendary',
    minWeight: 100.0,
    maxWeight: 180.0,
    basePrice: 3500,
    catchDifficulty: 10,
    spawnChance: 1,
    description: 'การ์โบราณที่รอดมานับล้านปี',
    emoji: '🦴',
  },
  {
    id: 'swamp_frog',
    name: 'Giant Bullfrog',
    nameEn: 'Giant Bullfrog',
    nameTh: 'กบบึงยักษ์',
    biome: 'swamp',
    rarity: 'uncommon',
    minWeight: 0.5,
    maxWeight: 2.0,
    basePrice: 100,
    catchDifficulty: 3,
    spawnChance: 18,
    description: 'กบขนาดใหญ่เสียงดังมาก',
    emoji: '🐸',
  },
  {
    id: 'swamp_salamander',
    name: 'Giant Salamander',
    nameEn: 'Giant Salamander',
    nameTh: 'ซาลาแมนเดอร์ยักษ์',
    biome: 'swamp',
    rarity: 'rare',
    minWeight: 3.0,
    maxWeight: 8.0,
    basePrice: 350,
    catchDifficulty: 6,
    spawnChance: 9,
    description: 'สัตว์สะเทินน้ำสะเทินบกยักษ์',
    emoji: '🦎',
  },
  {
    id: 'swamp_anchovy',
    name: 'Swamp Anchovy',
    nameEn: 'Swamp Anchovy',
    nameTh: 'กะตักบึง',
    biome: 'swamp',
    rarity: 'common',
    minWeight: 0.1,
    maxWeight: 0.4,
    basePrice: 30,
    catchDifficulty: 1,
    spawnChance: 30,
    description: 'ปลาเล็กฝูงใหญ่',
    emoji: '🐟',
  },
  {
    id: 'swamp_tigerfish',
    name: 'Swamp Tigerfish',
    nameEn: 'Swamp Tigerfish',
    nameTh: 'ปลาเสือบึง',
    biome: 'swamp',
    rarity: 'epic',
    minWeight: 8.0,
    maxWeight: 18.0,
    basePrice: 700,
    catchDifficulty: 8,
    spawnChance: 5,
    description: 'ปลาดุร้ายมีฟันคม',
    emoji: '🐅',
  },
  {
    id: 'swamp_electric_eel',
    name: 'Electric Eel',
    nameEn: 'Electric Eel',
    nameTh: 'ปลาไหลไฟฟ้า',
    biome: 'swamp',
    rarity: 'epic',
    minWeight: 10.0,
    maxWeight: 25.0,
    basePrice: 800,
    catchDifficulty: 9,
    spawnChance: 4,
    description: 'ปลาไหลปล่อยกระแสไฟฟ้า',
    emoji: '⚡',
  },
  {
    id: 'swamp_piranha',
    name: 'Red Piranha',
    nameEn: 'Red Piranha',
    nameTh: 'ปิรันย่าแดง',
    biome: 'swamp',
    rarity: 'rare',
    minWeight: 1.0,
    maxWeight: 3.0,
    basePrice: 260,
    catchDifficulty: 7,
    spawnChance: 11,
    description: 'ปลาฉลามน้ำจืดฟันคม',
    emoji: '🦷',
  },
  {
    id: 'swamp_arapaima_gold',
    name: 'Golden Arapaima',
    nameEn: 'Golden Arapaima',
    nameTh: 'อารพายมาทอง',
    biome: 'swamp',
    rarity: 'legendary',
    minWeight: 100.0,
    maxWeight: 250.0,
    basePrice: 4000,
    catchDifficulty: 10,
    spawnChance: 1,
    description: 'อารพายมาสีทองในตำนาน',
    emoji: '👑',
  },
];

// Helper functions
export function getFishByBiome(biome: BiomeType): Fish[] {
  return FISH_DATABASE.filter(fish => fish.biome === biome);
}

export function getFishById(fishId: string): Fish | undefined {
  return FISH_DATABASE.find(fish => fish.id === fishId);
}

export function getFishByRarity(rarity: Rarity): Fish[] {
  return FISH_DATABASE.filter(fish => fish.rarity === rarity);
}

export function getRandomFishForBiome(
  biome: BiomeType,
  rarityBonus: number = 0 // % เพิ่มโอกาสได้ rarity สูง
): Fish | null {
  const biomeFish = getFishByBiome(biome);
  if (biomeFish.length === 0) return null;

  // สร้าง weighted random pool
  const weightedPool: Fish[] = [];
  
  biomeFish.forEach(fish => {
    let spawnChance = fish.spawnChance;
    
    // ถ้ามี rarity bonus ให้เพิ่ม chance สำหรับปลา rare
    if (rarityBonus > 0) {
      const rarityMultiplier = {
        common: 1,
        uncommon: 1 + (rarityBonus * 0.01),
        rare: 1 + (rarityBonus * 0.02),
        epic: 1 + (rarityBonus * 0.03),
        legendary: 1 + (rarityBonus * 0.05),
      };
      spawnChance *= rarityMultiplier[fish.rarity];
    }
    
    // เพิ่มปลาเข้าไปตามน้ำหนัก
    for (let i = 0; i < Math.ceil(spawnChance); i++) {
      weightedPool.push(fish);
    }
  });

  // สุ่มปลา
  return weightedPool[Math.floor(Math.random() * weightedPool.length)];
}

export function calculateFishWeight(fish: Fish): number {
  return Math.random() * (fish.maxWeight - fish.minWeight) + fish.minWeight;
}

export function calculateFishPrice(fish: Fish, weight: number): number {
  return Math.round(fish.basePrice * weight);
}
