import { 
  User, 
  WorkoutTemplate, 
  Exercise, 
  Badge, 
  Challenge, 
  LeaderboardEntry,
  Meal,
  LiveClass 
} from './types';

// Mock User
export const mockUser: User = {
  id: 'user-1',
  nickname: 'Deen',
  username: 'deen123',
  weight: 70,
  height: 175,
  age: 28,
  gender: 'male',
  tier: 'gold',
  points: 2450,
  streakDays: 12,
  createdAt: new Date('2024-01-15'),
};

// Mock Exercises
export const mockExercises: Exercise[] = [
  {
    id: 'ex-1',
    name: 'Jumping Jacks',
    nameEn: 'Jumping Jacks',
    nameTh: 'กระโดดตบ',
    duration: 45,
    reps: 20,
    restTime: 15,
    category: 'hiit',
    difficulty: 'beginner',
    targetMuscles: ['legs', 'cardio'],
    instructions: ['Stand with feet together', 'Jump and spread legs while raising arms', 'Return to starting position'],
  },
  {
    id: 'ex-2',
    name: 'Push-ups',
    nameEn: 'Push-ups',
    nameTh: 'วิดพื้น',
    duration: 60,
    reps: 15,
    restTime: 20,
    category: 'strength',
    difficulty: 'intermediate',
    targetMuscles: ['chest', 'triceps', 'shoulders'],
    instructions: ['Start in plank position', 'Lower chest to ground', 'Push back up'],
  },
  {
    id: 'ex-3',
    name: 'Mountain Climbers',
    nameEn: 'Mountain Climbers',
    nameTh: 'ไต่เขา',
    duration: 45,
    reps: 30,
    restTime: 15,
    category: 'hiit',
    difficulty: 'intermediate',
    targetMuscles: ['core', 'legs', 'cardio'],
    instructions: ['Start in plank position', 'Drive knees toward chest alternately', 'Keep core engaged'],
  },
  {
    id: 'ex-4',
    name: 'Squats',
    nameEn: 'Squats',
    nameTh: 'สควอท',
    duration: 60,
    reps: 20,
    restTime: 20,
    category: 'strength',
    difficulty: 'beginner',
    targetMuscles: ['quads', 'glutes', 'hamstrings'],
    instructions: ['Stand with feet shoulder-width apart', 'Lower hips back and down', 'Keep chest up'],
  },
  {
    id: 'ex-5',
    name: 'Burpees',
    nameEn: 'Burpees',
    nameTh: 'เบอร์ปี้',
    duration: 60,
    reps: 10,
    restTime: 30,
    category: 'hiit',
    difficulty: 'advanced',
    targetMuscles: ['full body'],
    instructions: ['Start standing', 'Drop to push-up', 'Jump back up with arms overhead'],
  },
  {
    id: 'ex-6',
    name: 'Plank Hold',
    nameEn: 'Plank Hold',
    nameTh: 'แพลงค์',
    duration: 45,
    restTime: 15,
    category: 'strength',
    difficulty: 'intermediate',
    targetMuscles: ['core', 'shoulders'],
    instructions: ['Hold plank position', 'Keep body straight', 'Engage core throughout'],
  },
  {
    id: 'ex-7',
    name: 'High Knees',
    nameEn: 'High Knees',
    nameTh: 'ยกเข่าสูง',
    duration: 45,
    reps: 40,
    restTime: 15,
    category: 'hiit',
    difficulty: 'beginner',
    targetMuscles: ['legs', 'cardio'],
    instructions: ['Run in place', 'Bring knees up high', 'Pump arms'],
  },
  {
    id: 'ex-8',
    name: 'Lunges',
    nameEn: 'Lunges',
    nameTh: 'ลันจ์',
    duration: 60,
    reps: 20,
    restTime: 20,
    category: 'strength',
    difficulty: 'intermediate',
    targetMuscles: ['quads', 'glutes', 'hamstrings'],
    instructions: ['Step forward', 'Lower back knee toward ground', 'Push back to start'],
  },
];

// Mock Workout Templates
export const mockWorkoutTemplates: WorkoutTemplate[] = [
  {
    id: 'wt-1',
    name: 'Morning HIIT Blast',
    nameEn: 'Morning HIIT Blast',
    nameTh: 'HIIT เช้าๆ',
    category: 'hiit',
    duration: 25,
    difficulty: 'intermediate',
    calories: 250,
    exercises: [mockExercises[0], mockExercises[2], mockExercises[4], mockExercises[6]],
    warmUp: [mockExercises[0]],
    coolDown: [mockExercises[5]],
  },
  {
    id: 'wt-2',
    name: 'Full Body Strength',
    nameEn: 'Full Body Strength',
    nameTh: 'เสริมสร้างกล้ามเนื้อทั้งตัว',
    category: 'strength',
    duration: 35,
    difficulty: 'intermediate',
    calories: 300,
    exercises: [mockExercises[1], mockExercises[3], mockExercises[5], mockExercises[7]],
    warmUp: [mockExercises[0]],
    coolDown: [mockExercises[5]],
  },
  {
    id: 'wt-3',
    name: 'Quick Circuit',
    nameEn: 'Quick Circuit',
    nameTh: 'เซอร์กิตเร็ว',
    category: 'circuit',
    duration: 20,
    difficulty: 'beginner',
    calories: 180,
    exercises: [mockExercises[0], mockExercises[3], mockExercises[6]],
    warmUp: [mockExercises[6]],
    coolDown: [mockExercises[5]],
  },
  {
    id: 'wt-4',
    name: 'Mobility Flow',
    nameEn: 'Mobility Flow',
    nameTh: 'ความยืดหยุ่น',
    category: 'mobility',
    duration: 15,
    difficulty: 'beginner',
    calories: 80,
    exercises: [mockExercises[5]],
    warmUp: [],
    coolDown: [],
  },
];

// Mock Badges
export const mockBadges: Badge[] = [
  {
    id: 'badge-1',
    name: 'First Workout',
    nameEn: 'First Workout',
    nameTh: 'ออกกำลังกายครั้งแรก',
    description: 'Complete your first workout',
    icon: '🏃',
    earnedAt: new Date('2024-01-16'),
    requirement: 'Complete 1 workout',
  },
  {
    id: 'badge-2',
    name: '7 Day Streak',
    nameEn: '7 Day Streak',
    nameTh: 'ต่อเนื่อง 7 วัน',
    description: 'Workout 7 days in a row',
    icon: '🔥',
    earnedAt: new Date('2024-01-22'),
    requirement: 'Maintain 7 day streak',
  },
  {
    id: 'badge-3',
    name: 'Calorie Crusher',
    nameEn: 'Calorie Crusher',
    nameTh: 'นักเผาผลาญ',
    description: 'Burn 1000 calories in a week',
    icon: '💪',
    earnedAt: new Date('2024-02-01'),
    requirement: 'Burn 1000 kcal in 7 days',
  },
  {
    id: 'badge-4',
    name: 'Early Bird',
    nameEn: 'Early Bird',
    nameTh: 'นกตื่นแต่เช้า',
    description: 'Complete 5 morning workouts',
    icon: '🌅',
    requirement: '5 workouts before 8 AM',
  },
  {
    id: 'badge-5',
    name: 'HIIT Master',
    nameEn: 'HIIT Master',
    nameTh: 'เจ้า HIIT',
    description: 'Complete 20 HIIT workouts',
    icon: '⚡',
    requirement: '20 HIIT workouts',
  },
];

// Mock Challenges
export const mockChallenges: Challenge[] = [
  {
    id: 'ch-1',
    name: 'Weekly Warrior',
    nameEn: 'Weekly Warrior',
    nameTh: 'นักสู้ประจำสัปดาห์',
    description: 'Complete 5 workouts this week',
    target: 5,
    current: 3,
    reward: 200,
    endDate: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000),
    type: 'weekly',
  },
  {
    id: 'ch-2',
    name: 'Calorie Goal',
    nameEn: 'Calorie Goal',
    nameTh: 'เป้าหมายแคลอรี่',
    description: 'Burn 2000 calories this week',
    target: 2000,
    current: 1420,
    reward: 300,
    endDate: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000),
    type: 'weekly',
  },
  {
    id: 'ch-3',
    name: 'Daily Move',
    nameEn: 'Daily Move',
    nameTh: 'เคลื่อนไหวประจำวัน',
    description: 'Complete any workout today',
    target: 1,
    current: 0,
    reward: 50,
    endDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000),
    type: 'daily',
  },
];

// Mock Leaderboard
export const mockLeaderboard: LeaderboardEntry[] = [
  { rank: 1, userId: 'u-1', nickname: 'FitnessPro', tier: 'diamond', points: 18500 },
  { rank: 2, userId: 'u-2', nickname: 'GymQueen', tier: 'diamond', points: 12300 },
  { rank: 3, userId: 'u-3', nickname: 'WorkoutKing', tier: 'diamond', points: 8700 },
  { rank: 4, userId: 'u-4', nickname: 'Deen', tier: 'platinum', points: 3450 },
  { rank: 5, userId: 'u-5', nickname: 'RunnerBee', tier: 'gold', points: 2100 },
  { rank: 6, userId: 'u-6', nickname: 'YogaMaster', tier: 'silver', points: 1850 },
  { rank: 7, userId: 'u-7', nickname: 'CardioFan', tier: 'silver', points: 1090 },
  { rank: 8, userId: 'u-8', nickname: 'NewbieFit', tier: 'bronze', points: 450 },
];

// Mock Meals
export const mockMeals: Meal[] = [
  {
    id: 'meal-1',
    name: 'Greek Yogurt Parfait',
    nameEn: 'Greek Yogurt Parfait',
    nameTh: 'โยเกิร์ตกรีกพาร์เฟต์',
    type: 'breakfast',
    calories: 320,
    protein: 18,
    carbs: 42,
    fats: 8,
    imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400',
    description: 'High-protein breakfast with berries and granola',
    benefits: ['High in protein', 'Probiotics for gut health', 'Sustained energy'],
  },
  {
    id: 'meal-2',
    name: 'Grilled Chicken Salad',
    nameEn: 'Grilled Chicken Salad',
    nameTh: 'สลัดอกไก่ย่าง',
    type: 'lunch',
    calories: 450,
    protein: 35,
    carbs: 28,
    fats: 22,
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400',
    description: 'Lean protein with fresh vegetables',
    benefits: ['High protein', 'Low carb', 'Rich in vitamins'],
  },
  {
    id: 'meal-3',
    name: 'Salmon with Quinoa',
    nameEn: 'Salmon with Quinoa',
    nameTh: 'แซลมอนกับควินัว',
    type: 'dinner',
    calories: 520,
    protein: 38,
    carbs: 35,
    fats: 24,
    imageUrl: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=400',
    description: 'Omega-rich dinner for muscle recovery',
    benefits: ['Omega-3 fatty acids', 'Complete protein', 'Anti-inflammatory'],
  },
  {
    id: 'meal-4',
    name: 'Protein Smoothie',
    nameEn: 'Protein Smoothie',
    nameTh: 'สมูทตี้โปรตีน',
    type: 'snack',
    calories: 250,
    protein: 25,
    carbs: 30,
    fats: 5,
    imageUrl: 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?w=400',
    description: 'Post-workout recovery shake',
    benefits: ['Fast absorbing protein', 'Muscle recovery', 'Natural ingredients'],
  },
];

// Mock Live Classes
export const mockLiveClasses: LiveClass[] = [
  {
    id: 'lc-1',
    title: 'Morning HIIT Power',
    titleEn: 'Morning HIIT Power',
    titleTh: 'HIIT พลังยามเช้า',
    instructor: 'Coach Mike',
    startTime: new Date(Date.now() + 2 * 60 * 60 * 1000),
    duration: 30,
    category: 'hiit',
    participants: 24,
    maxParticipants: 50,
    isRsvped: false,
  },
  {
    id: 'lc-2',
    title: 'Strength Builder',
    titleEn: 'Strength Builder',
    titleTh: 'สร้างความแข็งแกร่ง',
    instructor: 'Coach Sarah',
    startTime: new Date(Date.now() + 5 * 60 * 60 * 1000),
    duration: 45,
    category: 'strength',
    participants: 18,
    maxParticipants: 30,
    isRsvped: true,
  },
  {
    id: 'lc-3',
    title: 'Evening Flow',
    titleEn: 'Evening Flow',
    titleTh: 'ฟลว์ยามเย็น',
    instructor: 'Coach Luna',
    startTime: new Date(Date.now() + 8 * 60 * 60 * 1000),
    duration: 40,
    category: 'mobility',
    participants: 12,
    maxParticipants: 25,
    isRsvped: false,
  },
];

// Mock Stats
export const mockStats = {
  calories: 420,
  caloriesGoal: 600,
  workoutTime: 45,
  sleep: 7.5,
  water: 6,
  waterGoal: 8,
  movement: 78,
  weeklyWorkouts: 4,
  weeklyWorkoutsGoal: 5,
  totalWorkouts: 48,
  totalCaloriesBurned: 12450,
  averageAccuracy: 87,
};

// Mock Session Summary
export const mockSessionSummary = {
  duration: 25,
  caloriesBurned: 280,
  exercisesCompleted: 8,
  repsTotal: 156,
  accuracyScore: 89,
  personalBests: 2,
  pointsEarned: 75,
};
